$env:GATEWAY_SECRET="localdemo"
$env:AGENT_ENABLE="true"
$env:AGENT_MODE="detect"
$env:AGENT_NEW_SERVICE_GRACE="0"
$env:AGENT_AI_ENABLE="true"
$env:AGENT_AI_BASE_URL="http://127.0.0.1:8787/v1"
$env:AGENT_AI_API_KEY="mock-key"
$env:AGENT_AI_MODEL="gemini-2.0-flash"
$env:REDIS_HOST="127.0.0.1"
$env:REDIS_PORT="6379"
$env:REDIS_PASSWORD=""
$env:REDIS_NO_TLS="true"
$env:LARK_WEBHOOK_URL="http://127.0.0.1:9000/lark"
Set-Location "C:\Users\Administrator\Desktop\Project"
.\versus-full.exe *>> versus-run.log
